# Generated by Django 3.2 on 2021-05-24 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('fee', models.FloatField()),
                ('max_capacity', models.IntegerField()),
                ('current_capacity', models.IntegerField(default=0)),
                ('sport_logo', models.FileField(upload_to='')),
                ('days', models.ManyToManyField(to='sport.Day')),
            ],
        ),
        migrations.CreateModel(
            name='TraineeSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_choice', models.CharField(choices=[('9AM : 11AM', '09.00 : 11.00 AM'), ('11AM: 13PM', '11.00 AM: 13.00 PM'), ('13PM : 15PM', '13.00 : 15.00 PM'), ('15PM : 17PM', '15.00 : 17.00 PM'), ('17PM : 19PM', '17.00 : 19.00 PM')], max_length=30)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.sport')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
