# Generated by Django 3.2 on 2021-05-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_remove_sport_sport_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='sport_logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
