# Generated by Django 3.2 on 2021-05-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_alter_medicalreport_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='disease',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
