# Generated by Django 3.2 on 2021-05-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_alter_medicalreport_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineesport',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
