# Generated by Django 3.2 on 2021-05-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_traineesport_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=100)),
                ('session', models.CharField(choices=[('9AM : 11AM', '09.00 : 11.00 AM'), ('11AM: 13PM', '11.00 AM: 13.00 PM'), ('13PM : 15PM', '13.00 : 15.00 PM'), ('15PM : 17PM', '15.00 : 17.00 PM'), ('17PM : 19PM', '17.00 : 19.00 PM')], max_length=30)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.sport')),
            ],
        ),
    ]
