# Generated by Django 3.2 on 2021-05-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
