# Generated by Django 3.2 on 2021-05-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_alter_trainer_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='age',
        ),
    ]
