# Generated by Django 3.2 on 2021-05-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_remove_trainer_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='session',
        ),
        migrations.AddField(
            model_name='trainer',
            name='sessions',
            field=models.ManyToManyField(to='sport.Session'),
        ),
        migrations.AlterField(
            model_name='traineesport',
            name='session_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.session'),
        ),
    ]
