# Generated by Django 3.2 on 2021-05-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0012_auto_20210526_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(max_length=50),
        ),
    ]
