# Generated by Django 3.2 on 2021-05-26 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0014_alter_session_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='session_choice',
        ),
        migrations.AddField(
            model_name='trainer',
            name='sessions',
            field=models.ManyToManyField(to='sport.Session'),
        ),
        migrations.AlterField(
            model_name='traineesport',
            name='session_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.session'),
        ),
    ]
