# Generated by Django 3.2 on 2021-05-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0015_auto_20210526_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
